# specify docker compose version
version: '3' 
# Container that should be started 
# When containers are opened with compose
# the networking is handled automatically.
services: 
  mongo-server: # database
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  app: # application
    build: . # location of Dockerfile
    ports: 
      - "80:3000" # exposed:in-image
