version: "3"

services:
  websocket_client:
    container_name: websocket_client
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000

  mongo:
    container_name: db
    image: mongo
    volumes:
      - /mongo/data/websocket_client:/data/db
    env_file:
      - .env
    ports:
      - "27017:27017"
    restart: always
