# specify docker compose version
version: '3' 
# Container that should be started 
# When containers are opened with compose
# the networking is handled automatically.
services: 
  web: # application
    build:
      context: . 
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
  mongo-server: # database
    container_name: mongo
    image: mongo
    volumes:
      - /home/var/lib/mongodb
    ports:
      - "27017:27017"
